<?php
/**
 * @file
 * A module that creates custom content-types and nodes automatically.
 */
use Drupal\Core\Entity;
use Drupal\node\Entity\Node;
/**
 * shows message while user visits every node
 */
function movies_details_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $nid = $node->id();
  }
  if((!empty($node))&&($node->hasField('movies_budget'))){
    $node = Node::load($nid);
    $movies_budget= $node->get('movies_budget')->value;
    $cofig_movies_budget = \Drupal::config('movies_details.admin_settings')->get('movies_budget');
    if(!empty($movies_budget)&&(!empty($cofig_movies_budget))){
      if($movies_budget>$cofig_movies_budget) {
        \Drupal::messenger()->addMessage("Movie is overBudget");
      } else{
        \Drupal::messenger()->addMessage("Movie is underbudget");
      }
    }
  }
}